### PR TITLE
Simplified remove task and avoid repeat task if not needed

### PR DESCRIPTION
**Pull request by jordigg**
Simplified the remove task and added conditions to don't repeat the change if not needed.

### CODE REVIEW

**Comment by noma4i** [comment]
Good addition. Noticed that you have changed Temp path. It was set as Public folder for purpose. Windows\temp is not always accessible especially Iv faced that on Win 2012 Server. Better approach is to evaluate ps code '$env:TEMP ' which will give you real temp for current user(depends how puppet was started) or default to always accessible Public folder which exists since WinXP.

**Comment by jordigg** [comment]
I can change that, will try to find a better suited folder. `$env:TEMP` is not always set as well, or that's what I've readed.
Maybe there's a temp folder on the Public folder. What I'm trying to do is just avoid copying the file everytime it runs since it recognized as a change but it really isn't.
Will research a bit and change that part. Will check other modules what's their approach.

**Comment by jordigg** [comment]
I'll give a try creating a custom fact as explained here: http://stackoverflow.com/a/35470313

**Comment by jordigg** [comment]
All set. Tested and working. Is now pulling the temp dir from the env variables. On my case was `C:\Users\jordi\AppData\Local\Temp` but it also looks for the system account variable in case no one is logged in.
Please check.

**Comment by noma4i** [comment]
As I remember Puppet is running under System user and thats why it can't see Win32::Registry::HKEY_CURRENT_USER cause there is now Current User branch in registry for him. I don't have win environment atm, have you checked that this plugin works correct if puppet is running as a daemon?

**Comment by jordigg** [comment]
Yes, it defaults to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\temp` with value `%SystemRoot%\TEMP` that translates to `C:\Windows\TEMP` on my Windows 10 Pro machine but should be the same on other Windows versions. No issues so far on my dev environment.

**Comment by noma4i** [comment]
Merged, version bumped and went to puppet-forge

**Pull request merged**
